### ISSUE TITLE
make 

### ISSUE THREAD

**Issue by zoloxo** [adibendahan/mysqlbeat#2] opened 2016-05-12 02:54 UTC
when i run make command on under mysqlbeat folder error happens
go build
# github.com/adibendahan/mysqlbeat/beater

../github.com/adibendahan/mysqlbeat/beater/mysqlbeat.go:474: b.Events undefined (type _beat.Beat has no field or method Events)
../github.com/adibendahan/mysqlbeat/beater/mysqlbeat.go:503: b.Events undefined (type *beat.Beat has no field or method Events)
make: *_\* [build] Error 2

**Comment by adibendahan** [comment] 2016-05-12 12:15
@zoloxo did you run `glide update --no-recursive`?

**Comment by adibendahan** [comment] 2016-05-13 22:58
So i've copied my repo into a new directory and tried to `make` and I got the same error, that's weird... not sure exactly why is this happening.

@zstyblik did you have any issues when you forked mysqlbeat?

**Comment by zstyblik** [comment] 2016-05-14 07:33
@adibendahan I believe I faced the same error. I don't think I have a solution, though. I've switched to stable version(v1.2.x) of [beats](https://github.com/elastic/beats/) and `vendor/` and [govendor](https://github.com/kardianos/govendor). These changes remain uncommitted, though, as they're dependency-management changes. Or so I've thought.

**Comment by adibendahan** [comment] 2016-05-14 12:07
@zstyblik thanks for the help, I'm not sure I understood how did you work around this issue.
Did you change the glide dependency of beats to the commit of 1.2 (ce5038e4946745488acb77b78e404cff09b765ee)? for some reason I cannot reproduce this issue on my machine...

@zoloxo can you try it?

**Comment by adibendahan** [comment] 2016-05-14 12:52
**Update:** I got a fresh Mac to test this on and I couldn't reproduce this issue there as well...

Steps I did:
1.  Installed homebrew `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
2. Run `brew install go`
3. Setup go path _(see script below)_
4. Run `brew install glide`
5. Download the latest mysqlbeat source off Github (put it under $gopath/src/github.com/adibendahan/mysqlbeat)
6. Run `glide update --no-recursive`
7. Run `make`

it builds with no issues ...

```
echo "Please enter your golang path (ex: $HOME/golang) :"
read gopath

mkdir $gopath
mkdir -p $gopath/src/github.com/adibendahan

export GOPATH=$gopath
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
```

**Comment by zstyblik** [comment] 2016-05-14 22:03
@adibendahan as I've said, I'm using different tool to manage dependencies. But yes, in the end, I'm using beats 1.2.x. I believe there were lot of changes in beats 5.0.0 and this might be one of them(I actually remember digging into beats source code and it just wasn't there) . The error might be the result of checking out the wrong dependency, somehow, or having different version of beats in a GOPATH. I honestly cannot say(right now).

**Comment by adibendahan** [comment] 2016-05-15 08:42
Since this is not reproducing when you use glide, I'm closing this issue.

**Closed as completed by adibendahan** 2016-05-15 08:42 UTC
Labels: help wanted
